# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
#  schedule:
#    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clone activity-log
        uses: actions/checkout@v4
        with:
          name: TheDanniCraft/activity-log
      - name: Run activity-log directly
        run: activity-log/src/index.js
      # - name: Update GitHub Activity
      #   uses: TheDanniCraft/activity-log@v1
      #   with:
      #     GITHUB_USERNAME: "raymundlin"
      #     GITHUB_TOKEN: ${{ secrets.ACTIONSECRET2024 }} # Ensure this matches the secret name in repository settings
