# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
#  schedule:
#    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clone activity-log
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/TheDanniCraft/activity-log.git
      - name: Run activity-log directly
        working-directory: ./activity-log
        env:
          GITHUB_USERNAME: "raymundlin"
          GITHUB_TOKEN: ${{ secrets.ACTIONSECRET2024 }} # Ensure this matches the secret name in repository settings
        run: |
          npm i -g @vercel/ncc
          npm i @actions/github
          ncc run src/index.js --license licenses.txt
